/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'takeo' at '17/01/03 10:32' with Gradle 3.2.1
 *
 * @author takeo, @date 17/01/03 10:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
