package com.test;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'takeo' at '17/01/03 10:32' with Gradle 3.2.1
 *
 * @author takeo, @date 17/01/03 10:32
 */

@SpringBootApplication
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        System.out.println("test");
        SpringApplication.run(Library.class, args);
    }
}
